name: Lint

on:
  ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "install linter"
        run: sudo apt-get install -y pylint
      - name: "run linter"
        run: pylint python
