name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: "docker build"
      run: docker buildx build --tag=meditations .
    - name: "cloud deploy"
      if ${{ github.ref == 'refs/heads/main' }}
      uses: ./.github/workflows/_deployment.yaml
      permissions:
        id-token: write
        contents: read
      with:
        environment: prod
        ref: ${{ github.sha }}
      secrets: inherit
